/// <reference path="../.astro/types.d.ts" />

// Cloudflare bindings. `Env` (DB, ASSETS) is generated by `npm run cf:types` into
// worker-configuration.d.ts from wrangler.jsonc, and refers to the two Cloudflare
// runtime types below. They are aliased here (instead of loading all of
// @cloudflare/workers-types globally) so they cannot clash with the DOM types that
// Astro's TypeScript config already provides.
type D1Database = import('@cloudflare/workers-types').D1Database;
type Fetcher = import('@cloudflare/workers-types').Fetcher;

// @astrojs/cloudflare v12 (Astro 5): bindings are reached through `locals.runtime.env`.
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
