-- 0001_initial_schema
--
-- Initial schema. Migrations are the authoritative history of the database: never edit
-- a migration that has been applied anywhere; add a new numbered file instead.
--
-- Conventions
--   * IDs are TEXT, generated by the application (crypto.randomUUID()). Public URLs use
--     slugs, never IDs.
--   * Timestamps are TEXT in ISO 8601 UTC (e.g. 2026-01-31T18:04:05Z).
--   * Money is stored as INTEGER cents plus an ISO 4217 currency code.
--   * Booleans are INTEGER 0/1 with a CHECK.
--   * JSON is used only for small presentation-only collections (badges, product detail
--     rows, quality notes, DIY materials/steps). Relationships are always tables.
--   * Foreign keys are enforced by D1.
--
-- The site curates PRODUCTS. RETAILERS provide OFFERS for those products. A product and
-- a retailer listing are different things, so they live in different tables.

-- ---------------------------------------------------------------------------
-- categories: a simple tree. Rows are data (managed later), not hard-coded logic.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
  id          TEXT PRIMARY KEY NOT NULL,
  slug        TEXT NOT NULL UNIQUE
                CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9-]*'),
  name        TEXT NOT NULL CHECK (length(name) > 0),
  description TEXT,
  parent_id   TEXT REFERENCES categories (id) ON DELETE RESTRICT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX idx_categories_parent ON categories (parent_id, sort_order);

-- ---------------------------------------------------------------------------
-- products: the canonical curated product.
-- Only review_status = 'approved' may ever be shown publicly.
-- review_notes are INTERNAL and must never be selected by public queries.
-- ---------------------------------------------------------------------------
CREATE TABLE products (
  id                 TEXT PRIMARY KEY NOT NULL,
  slug               TEXT NOT NULL UNIQUE
                       CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9-]*'),
  name               TEXT NOT NULL CHECK (length(name) > 0),
  summary            TEXT NOT NULL,
  description        TEXT,
  category_id        TEXT NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,

  -- JSON arrays (presentation only)
  quality_notes_json TEXT
                       CHECK (quality_notes_json IS NULL
                              OR (json_valid(quality_notes_json) AND json_type(quality_notes_json) = 'array')),
  details_json       TEXT
                       CHECK (details_json IS NULL
                              OR (json_valid(details_json) AND json_type(details_json) = 'array')),
  badges_json        TEXT
                       CHECK (badges_json IS NULL
                              OR (json_valid(badges_json) AND json_type(badges_json) = 'array')),

  image_url          TEXT,
  image_alt          TEXT,

  review_status      TEXT NOT NULL DEFAULT 'pending'
                       CHECK (review_status IN ('pending', 'approved', 'rejected')),
  review_notes       TEXT, -- INTERNAL ONLY

  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  reviewed_at        TEXT,

  -- A product that has been approved or rejected must record when it was reviewed.
  CHECK (review_status = 'pending' OR reviewed_at IS NOT NULL)
);

CREATE INDEX idx_products_status_category ON products (review_status, category_id);
CREATE INDEX idx_products_category ON products (category_id);

-- ---------------------------------------------------------------------------
-- retailers: outside stores/vendors.
-- ---------------------------------------------------------------------------
CREATE TABLE retailers (
  id          TEXT PRIMARY KEY NOT NULL,
  slug        TEXT NOT NULL UNIQUE
                CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9-]*'),
  name        TEXT NOT NULL CHECK (length(name) > 0),
  website_url TEXT NOT NULL,
  is_active   INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- product_offers: a retailer's listing for a product. One product can have many.
-- affiliate_url is reserved for the future; nothing generates it yet.
-- ---------------------------------------------------------------------------
CREATE TABLE product_offers (
  id                  TEXT PRIMARY KEY NOT NULL,
  product_id          TEXT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  retailer_id         TEXT NOT NULL REFERENCES retailers (id) ON DELETE RESTRICT,
  retailer_product_id TEXT, -- the retailer's own SKU/listing id, when known
  product_url         TEXT NOT NULL,
  affiliate_url       TEXT, -- future use
  price_cents         INTEGER CHECK (price_cents IS NULL OR price_cents >= 0),
  currency            TEXT NOT NULL DEFAULT 'USD'
                        CHECK (length(currency) = 3 AND currency = upper(currency)),
  availability        TEXT NOT NULL DEFAULT 'unknown'
                        CHECK (availability IN ('in_stock', 'out_of_stock', 'discontinued', 'unknown')),
  is_primary          INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  last_checked_at     TEXT, -- when price/listing info was last verified
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),

  -- The same listing cannot be recorded twice.
  UNIQUE (retailer_id, product_url),
  UNIQUE (retailer_id, retailer_product_id)
);

CREATE INDEX idx_offers_product ON product_offers (product_id);
CREATE INDEX idx_offers_retailer ON product_offers (retailer_id);

-- At most one preferred offer per product.
CREATE UNIQUE INDEX ux_offers_one_primary_per_product
  ON product_offers (product_id) WHERE is_primary = 1;

-- ---------------------------------------------------------------------------
-- diy_projects: authored project content. Deliberately not a CMS.
-- ---------------------------------------------------------------------------
CREATE TABLE diy_projects (
  id             TEXT PRIMARY KEY NOT NULL,
  slug           TEXT NOT NULL UNIQUE
                   CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9-]*'),
  title          TEXT NOT NULL CHECK (length(title) > 0),
  summary        TEXT NOT NULL,
  body           TEXT, -- future long-form content
  materials_json TEXT
                   CHECK (materials_json IS NULL
                          OR (json_valid(materials_json) AND json_type(materials_json) = 'array')),
  steps_json     TEXT
                   CHECK (steps_json IS NULL
                          OR (json_valid(steps_json) AND json_type(steps_json) = 'array')),
  difficulty     TEXT NOT NULL DEFAULT 'easy' CHECK (difficulty IN ('easy', 'medium', 'hard')),
  estimated_time TEXT,
  image_url      TEXT,
  image_alt      TEXT,
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_diy_projects_status ON diy_projects (status);

-- ---------------------------------------------------------------------------
-- diy_project_products: which products a project uses, in a deliberate order.
-- ---------------------------------------------------------------------------
CREATE TABLE diy_project_products (
  project_id TEXT NOT NULL REFERENCES diy_projects (id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (project_id, product_id)
);

CREATE INDEX idx_diy_project_products_product ON diy_project_products (product_id);
