/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cdf2d2ac412db0c5397eb874e1303361)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
